### ISSUE TITLE
nake build doesn't run properly

### ISSUE THREAD

**Issue by kzerot** [pragmagic/godot-nim-stub#1]
**OS:** Win 7 x64
While I tried to run "nake build" in project directory:
nakelib.nim(177)         cd
os.nim(278)              setCurrentDir
oserr.nim(113)           raiseOSError
Error: unhandled exception: ÐÐµ ÑƒÐ´Ð°ÐµÑ‚ÑÑ Ð½Ð°Ð¹Ñ‚Ð¸ ÑƒÐºÐ°Ð·Ð°Ð½Ð½Ñ‹Ð¹ Ñ„Ð°Ð¹Ð».

**Comment by endragor** [comment]
This shouldn't be an issue any longer (for a long time now...). Please let me know if there still is a problem.
