### ISSUE TITLE
i get this error when i open godot-nim stub

### ISSUE THREAD

**Issue by eminvergil** [pragmagic/godot-nim-stub#11]
ERROR: open_dynamic_library: Can't open dynamic library: /home/emin/Documents/gameprozs/nim-try-3/_dlls/nim_linux_64.so. Error: /snap/godot/27/bin/../lib/nim_linux_64.so: cannot open shared object file: No such file or directory
   At: drivers/unix/os_unix.cpp:379.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:317.
ERROR: init_library: No nativescript_init in "res://_dlls/nim_linux_64.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1054.
ERROR: terminate: No valid library handle, can't terminate GDNative object
   At: modules/gdnative/gdnative.cpp:223.
ERROR: open_dynamic_library: Can't open dynamic library: /home/emin/Documents/gameprozs/nim-try-3/_dlls/nim_linux_64.so. Error: /snap/godot/27/bin/../lib/nim_linux_64.so: cannot open shared object file: No such file or directory
   At: drivers/unix/os_unix.cpp:379.

**Comment by endragor** [comment]
Did you follow the instructions in README and run `nake build`? It seems you didn't build the library.

**Comment by eminvergil** [comment]
yes i followed instructions . **nake build** gives another error 

![1](https://user-images.githubusercontent.com/17277419/47900137-e72bdf80-de8c-11e8-871d-632b80630101.png)

**Comment by eminvergil** [comment]
cause of this error is invalid GODOT_BIN path . i solved it now . thx
