### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lkadalski** [pragmagic/godot-nim-stub#5]
Hello, I'm new into nim language but just wanted to test your package.
I have nim lang ver 0.18.0 and trying to run this stub ./nim_linux_64.so.
The only thing on output is:
Segmentation fault (core dumped).

Background: Godot v3.0.1 stable, Linux Mint 17.3.
Perhaps you need more information :)

**Comment by endragor** [comment]
If this is still relevant to you, could you please check again? https://github.com/pragmagic/godot-nim/commit/dc6ebaf5757b82436d714a779855207c6009afe4 should have fixed that problem.

**Comment by endragor** [comment]
Closing, assuming this was fixed in godot-nim.
