### ISSUE TITLE
Nakefile defaults to Godot application directory instead of project

### ISSUE THREAD

**Issue by hcphoenix** [pragmagic/godot-nim-stub#7]
Tested on OS X High Sierra.

Running ``` nake build ``` logs the following command arguments:
```
arguments
0: /Applications/Godot.app/Contents/MacOS/Godot
1: --gdnative-generate-json-api
2: _godotapi/api.json
Current path: /Applications/Godot.app/Contents/Resources
```
Godot then encounters a file permissions error as it attempts to write to its own Resources directory. This issue occurs despite being navigated to the project directory when building the nakefile from the command line.

**Comment by hcphoenix** [comment]
``` nake build ``` completes successfully when I change line 21 of the nakefile to
```
direShell(godotBin, "--gdnative-generate-json-api", getAppDir()/jsonFile)
```
Would you like me to submit a PR?

**Comment by endragor** [comment]
nake is supposed to set the nakefile's directory as the working directory. I wonder why it didn't work in your case. What's the exact value of `GODOT_BIN` variable that you set and what does it output if you add `echo "CURRENT DIR: ", getCurrentDir()` after the `direShell` call that you mentioned?

**Comment by hcphoenix** [comment]
``` GODOT_BIN ``` is ``` /Applications/Godot.app/Contents/MacOS/Godot ```, output for ``` CURRENT_DIR ``` is ``` /Users/cadence/Repos/godot-nim-stub ```.

**Comment by DrMoriarty** [comment]
@endragor Any fix for that?
I have the same issue. Macosx 10.13.4, Godot 3.0.4
export GODOT_BIN=/Applications/Godot3.app/Contents/MacOS/Godot 
```
bash-3.2$ nake build
arguments
0: /Applications/Godot3.app/Contents/MacOS/Godot
1: --gdnative-generate-json-api
2: _godotapi/api.json
Current path: /Applications/Godot3.app/Contents/Resources
OpenGL ES 3.0 Renderer: NVIDIA GeForce GT 1030 OpenGL Engine
ERROR: save_file: Condition ' !file ' is true. returned: ERR_FILE_CANT_WRITE
   At: modules/gdnative/nativescript/api_generator.cpp:47.
ERROR: init: Failed to generate C API

   At: modules/gdnative/nativescript/nativescript.cpp:900.
Failed to generate api.json
```

**Comment by endragor** [comment]
Please check if it works now.
