### ISSUE TITLE
Unsafe threading?

### ISSUE THREAD

**Issue by hcphoenix** [pragmagic/godot-nim-stub#8]
Tested on OS X High Sierra with the latest stable Godot release.

The following is frequently logged to Godot's console in the stub project:
``` A foreign thread is created, but app is compiled without --threads:on. Bad things will happen if Nim code is invoked from this thread. ```
Either the nakefile should pass this flag to ``` nimble c ``` by default, or the readme should make it clear that this warning can be ignored (and why) if it isn't possible to suppress it.

**Comment by endragor** [comment]
Added a clarification to the message itself in https://github.com/pragmagic/godot-nim/commit/a1d14819678b9406e5927f73019fdb67dbcf7a62.
You can ignore this warning if it comes when you run the editor as the editor creates some threads after loading the Nim library, and the game itself doesn't create any threads.

**Comment by veksha** [comment]
FYI:
I was having crashes when using AssetLib tab in Godot until i saw console message spam "A foreign thread is created, but app is compiled without --threads:on ..." and decided to comment out that message from `godotnim.nim`

now i have no crashes.
